{
  description = "Dev environment for blau-bluer — Two Trees Bluer 3D printer mods, tuning, and slicer profiles";

  inputs = {
    # git+https instead of the github: scheme — the latter resolves revisions
    # through api.github.com, which this network blocks.
    nixpkgs.url = "git+https://github.com/NixOS/nixpkgs?ref=nixos-26.05&shallow=1";

    flake-utils.url = "git+https://github.com/numtide/flake-utils?shallow=1";

    treefmt-nix.url = "git+https://github.com/numtide/treefmt-nix?shallow=1";
    treefmt-nix.inputs.nixpkgs.follows = "nixpkgs";
  };

  outputs =
    {
      nixpkgs,
      flake-utils,
      treefmt-nix,
      ...
    }:
    flake-utils.lib.eachDefaultSystem (
      system:
      let
        pkgs = nixpkgs.legacyPackages.${system};

        # One formatter per language. libfive Scheme (.scm) and OpenSCAD
        # (.scad) have no standard formatter and are left untouched.
        treefmtEval = treefmt-nix.lib.evalModule pkgs {
          projectRootFile = "flake.nix";
          programs.nixfmt.enable = true; # Nix
          programs.stylua.enable = true; # Lua
          programs.prettier.enable = true; # Markdown
          settings.global.excludes = [
            # Machine-generated by IceSL — keep exactly as exported.
            "ICESL/settings/*"
          ];
        };
      in
      {
        devShells.default = pkgs.mkShell {
          packages = with pkgs; [
            lefthook
            libfive # Studio + Guile bindings for the .scm CAD models
            openscad
          ];
        };

        # `nix fmt` runs treefmt across the repo.
        formatter = treefmtEval.config.build.wrapper;

        # `nix flake check` verifies everything is formatted.
        checks.formatting = treefmtEval.config.build.check ./.;
      }
    );
}
